### ISSUE TITLE
queuecleaner not cleaning everything up

### ISSUE THREAD

**Issue by ookla-ariel-ride** [RandomNinjaAtk/docker-sonarr-extended#10]
I have noticed queuecleaner script is not cleaning up all failed downloads.  it just says:

QueueCleaner :: 1.0.007 :: No items in queue to clean up...

I have about 75 failed items in the queue.  Occasionally it might clean up a couple of them.  What should I provide to help debug this?

**Comment by RandomNinjaAtk** [comment]
Are the failed items marked as warning or failed?

https://github.com/RandomNinjaAtk/docker-sonarr-extended/blob/a459d093973f92262d004ddee9950ffe33e3fe52/root/scripts/QueueCleaner.bash#L32

Right now it only removes items that are considered completed, but with a warning state. Which I believe is indicated by a yellow icon/highlight.

**Comment by ookla-ariel-ride** [comment]
thanks for the update on this.  Your feature works great, the built-in option of sonarr doesn't seem to work that well.  Would be great if you extended your feature to cover failed downloads as well, but understand if you won't.
