### ISSUE TITLE
[Question] Plex Notify Script Update?

### ISSUE THREAD

**Issue by justinglock40** [RandomNinjaAtk/docker-sonarr-extended#12]
Afternoon. I just wanted to inquire whether you'd be updating your Plex Notify script to use the API scan instead of the CLI Scan since Plex says that will be deprecated in a future undisclosed version?

Thanks for what we have available now! Works great!!

**Comment by RandomNinjaAtk** [comment]
This is the first I am hearing this, so you have any links to information on it? 

If I can make the change, I will...

**Comment by justinglock40** [comment]
Alright so I figured out what was happening. You're 100% correct. Your script is already using the API operations.

I had the older Plex Autoscan set to run a cron job once a day to catch things that were missed during scans requests.

So that uses the Plex CLI Scanner that triggers a warning in the log that says "--scan is deprecated and will be removed in future versions of Plex Media Server." 

So because I forgot about that cron job that I was attributing that warning message to your script which was incorrect on my part.

So please close and disregard this. Thank you!

**Comment by justinglock40** [comment]
But this is the message you get from the command line scanner.

![image](https://user-images.githubusercontent.com/23133649/208146427-db1640b8-fb46-45b9-8d66-f4224f93b2bb.jpeg)

**Comment by RandomNinjaAtk** [comment]
Have you actually reviewed the script code? Thats not what this script uses, see here:
https://github.com/RandomNinjaAtk/docker-sonarr-extended/blob/d91667ac52de01adb242133853472712197179aa/root/scripts/PlexNotify.bash#L91

**Comment by justinglock40** [comment]
Yea we're on the same page. Your script was not causing this message. 

It was an older script from someone else that I had running as a cron job that was triggering the message.

So, yes, this is irrelevant.

**Comment by RandomNinjaAtk** [comment]
@justinglock40 Sorry for confusion with my last message, I only saw your last comment, not the one before it where you'd already figured it out and said the same thing...
