### ISSUE TITLE
TRaSH Guides updated to new format - update scripts to pull from .json files?

### ISSUE THREAD

**Issue by philmichel** [RandomNinjaAtk/docker-sonarr-extended#15]
Hi there,

it seems like the TRaSH guides were updated such that most of the data that the AutoConfig.bash script pulls in is no longer found. This data used to be stored in .md files in the TRaSH repo, but it is now actually broken out into .json files. 

For instance, the Sonarr recommended naming scheme is now located at: 
[https://github.com/TRaSH-/Guides/blob/master/docs/json/sonarr/naming/sonarr-naming.json](https://github.com/TRaSH-/Guides/blob/master/docs/json/sonarr/naming/sonarr-naming.json)

I think this should actually make it easier to pull in information in the scripts and more reliable, but it does require updates. The same would be true for radarr-extended.

Just wanted to point it out here in case this wasn't on the roadmap yet. I think this change to the TRaSH guides only happened a few weeks ago.

Many thanks as always for your work on these awesome docker images!

**Comment by RandomNinjaAtk** [comment]
Thanks for the info! That will make it easier, I'll look into incorporating it soon...
