### ISSUE TITLE
Docker image overwrites edits to custom formats

### ISSUE THREAD

**Issue by quadcom** [RandomNinjaAtk/docker-sonarr-extended#16]
I have edited the custom formats for SDR three times. The existing custom type filters out HDR content, specifically for **only** 2160p content. I have come across many 1080p releases that are a variety of HDR that I want to filter out. The edit I made to the existing filter was to remove the 2160p requirement. But when the container restarts, the custom type is restored to its default config.

**Comment by RandomNinjaAtk** [comment]
Sounds like you need to modify your Recyclarr config, because you likely have SDR included and its applying it from trash guides, which overwrites your changes....

So TLDR: Update your recyclar config and remove SDR...
