### ISSUE TITLE
Question about QueueCleaner...

### ISSUE THREAD

**Issue by quadcom** [RandomNinjaAtk/docker-sonarr-extended#17]
I use an external Seedbox, so downloads need to be synced to my local server for processing. This takes time, Long enough for the queuecleaner to wipe anything waiting for import. The files 'will' be there soon, just not in time for them to be deleted from the client. That cancels out the import process and flags the previous download as failed.

Is there any way to modify the script so that it will only clear entries that have been imported correctly?

I'm finding that now using Sonarr; I manually have to clear rtorrent of finished, unseeding DLs **and** I also have to delete the synced files from the monitored DIR after the import happens. No biggie, but automating things would be nicer.

**Comment by RandomNinjaAtk** [comment]
The script only removes downloads that are reported as "completed" or "failed", with completed requiring a "warning" sub status...

See here: https://github.com/RandomNinjaAtk/docker-sonarr-extended/blob/559ace3b392a5883a95e07dd9ee2ca0773eeb6ef/root/scripts/QueueCleaner.bash#L32-L35

So nothing should be removed that is considered a good completed download, if it is, then its likely an issue with how Sonarr tracks files and will need to be fixed upstream..
