### ISSUE TITLE
Script AutoConfig and Extras not configurable

### ISSUE THREAD

**Issue by RickL1999** [RandomNinjaAtk/docker-sonarr-extended#2]
I replaced my existing Sonarr install with this sonarr-extended after I had a good experience with your docker-amtd container for Radarr. 

As I understand it AutoConfig is necessary to setup the other scripts in Sonarr. But I found out the hard way it enables metadata, uses different media management and file naming. For my setup this is not wanted. 
Commenting out those parts of the script is useless because it is overwritten on start. So disabled this feature for now and restored my config.

Also I would like to keep the Capital letter folder-naming for extra's of the AMTD container for consistency reasons. 

I hope some changes can be made to accomplish this.

**Comment by RandomNinjaAtk** [comment]
Glad to hear that your using this project, but for the configuration, you can manually map the scripts, you don't have to use auto-configure.

AMTD did not support Sonarr, so there is no compatibility issues in folder naming because it did not exist then. I'm not likely to change the capitalization unless it breaks functionality with the intended use case, which as of now, it does not as far as I can tell. So there is no reason to adjust it besides personal taste/preference and everyone is likely to have a different preference.

**Comment by RickL1999** [comment]
I already had Behind The Scenes, Trailers and Other folders in my TV library.
The default naming scheme of Sonarr's series and season folders are capitalized and the recommended settings from TRaSH Guides are also capitalized. So why not have everything the same?

AMTD used capitalized folders but now the Radarr version of this container uses lowercase. Resulting in duplicates. But that is an issue for the other GitHub repo of course.

**Comment by RandomNinjaAtk** [comment]
Sonarr doesn't support these extras, what you're referring to is called Specials or Season 00. 

The feature here is designed for this only: 
https://support.plex.tv/articles/local-files-for-tv-show-trailers-and-extras/

Sonarr cannot track this data and you should not be mixing it with normal sonarr specials/season 00 for that reason.

**Comment by RickL1999** [comment]
I am not referring to Specials or S00 since those are listed in the TVDB with metadata, which are tracked by Sonarr and show up in Plex under Seasons.

I know that Plex support page like the back of my hand and this is what it says:
Where Extra_Directory_Type is one of:
Behind The Scenes
Deleted Scenes
Featurettes
Interviews
Scenes
Shorts
Trailers
Other

In Plex after refreshing the metadata of the serie, video files in these folders show up in a separate Extras category after the seasons.

And I know Sonarr and Radarr as well don't support tracking these files in the Extras directory's.

**Comment by RandomNinjaAtk** [comment]
I've validated extras are working as expected with Plex. I don't see anything to do here other than your request to use different capitalization, which is just a personal preference.
