### ISSUE TITLE
Feature Request: Add youtube dl functionality 

### ISSUE THREAD

**Issue by itsgiff** [RandomNinjaAtk/docker-sonarr-extended#20]
Are you able to add the functionality?

https://hub.docker.com/r/whatdaybob/sonarr_youtubedl

**Comment by RandomNinjaAtk** [comment]
I could look into it, or use it for inspiration to write my own version

**Comment by RandomNinjaAtk** [comment]
This should now be implemented with my own custom script... You just need to enable the script using the new parameter...  (https://github.com/RandomNinjaAtk/docker-sonarr-extended/commit/9a0471c067d3ba4270e2039bf3f731a5eff3dbae)

Keep in mind, this has had extremely little testing...

**Comment by itsgiff** [comment]
Nice work!!  I will test it tomorrow.  Thank you so much.
