### ISSUE TITLE
Can't run scripts permission denied

### ISSUE THREAD

**Issue by sea3pea0** [RandomNinjaAtk/docker-sonarr-extended#36]
Whenever I try to set up any of the extended scripts to work with the custom script connect feature I get a permission denied error.
I have this set in my docker container environment:
``
      - PGID=1000
      - PUID=1000
``
User/Group 1000 owns the directory where the extended scripts are and permissions are wide open. However in the container, the /app/sonarr/bin directory is owned by root. What do I need to do to get the scripts working?
``
 -- : An error occurred trying to start process '/scripts/DailySeriesEpisodeTrimmer.bash' with working directory '/app/sonarr/bin'. Permission denied
``

**Comment by RandomNinjaAtk** [comment]
That's the wrong location, you need to use the /config/extended/scripts/<script_name>

**Comment by sea3pea0** [comment]
Thank that was it!

**Comment by RandomNinjaAtk** [comment]
For future reference, checkout the wiki: https://github.com/RandomNinjaAtk/docker-sonarr-extended/wiki/DailySeriesEpisodeTrimmer.bash

**Comment by sea3pea0** [comment]
Got it thank you
