### ISSUE TITLE
troubleshooting a Sonarr API access issue......

### ISSUE THREAD

**Issue by quadcom** [RandomNinjaAtk/docker-sonarr-extended#38]
I just wanted to ask if you might know if anything in the extended Docker container might stop API access to Sonarr via `/api` ?

I know the docs on the API reference `/api/v3`

I'm running HAOS, and there is an integration in HACS that will pull in recently added shows. I can see the code hooking into `/api` instead of `/api/v3`.

When connecting to `/api`, my response is blank. Hooking into `/api/v3` I get a proper JSON output.

But other people running the same Sonarr v3 version as I am, still have access to `/api` and pulls are working fine for them. Specifically, the Windows build of Sonarr responds to `/api` whereas the Docker container version does not.

If I go to the Sonarr Discord and mention 'extended' I get shoowed away. They don't want to look at it. So my first stop is here to see if anything in the extended might be the cause of the problem.

**Comment by quadcom** [comment]
found the problem

**Comment by RandomNinjaAtk** [comment]
If you found the solution, might benefit others if you post it here....

**Comment by quadcom** [comment]
Not really a solution but an explanation.

The Python code in the HAOS addon calls on Sonarr's API v2. API v2 is functional in Sonarr v3 and lower; however, Sonarr v4 (which is what I am using) has dropped support for API v2. So while the API calls on other people's systems are working, it's because they are still running Sonarr v3, which accepts the older API calls. Once Sonarr v4 is fully released, everyone else will have the same errors once they upgrade.

Currently digging through the code and getting some assistance from a Python guy from a Reddit thread to try and figure out a patch. The original maintainer of the project archived it back in 2022 sometime.
