### ISSUE TITLE
Unmonitor Daily Series > 14 days

### ISSUE THREAD

**Issue by ookla-ariel-ride** [RandomNinjaAtk/docker-sonarr-extended#5]
Could the script that prunes daily series to 14 days also update sonarr to unmonitor those episodes?

**Comment by ookla-ariel-ride** [comment]
looks like this does happen, closing request

**Comment by itsgiff** [comment]
How often does this run?

**Comment by RandomNinjaAtk** [comment]
@itsgiff yeah, runs every import. But only does something if applicable...
