### ISSUE TITLE
Plex script not working

### ISSUE THREAD

**Issue by cherryontopknife** [RandomNinjaAtk/docker-sonarr-extended#7]
I have my plex URL and token setup, but nothing seems to happen when one of the qualifying events occurs [import, rename, etc.]. I renamed a show and watched the sonarr log. Nothing in the log indicated that the script was executed, and plex itself did not update. any ideas? i checked the wiki but there's no section for the plex script.

Thanks in advance.

**Comment by cherryontopknife** [comment]
it works great in radarr. not sure what the issue is with sonarr. the configs are almost exactly the same.

**Comment by RandomNinjaAtk** [comment]
Just added the wiki info, almost a complete copy/pasta from Radarr's: 
https://github.com/RandomNinjaAtk/docker-sonarr-extended/wiki/PlexNotify.bash

It's essentially the same script but tweaked for sonarr. You should check the script log file to see what is going on....

**Comment by cherryontopknife** [comment]
looks like you missed an instance of "movie" in the last paragraph on the new wiki entry.

i found the log, and i believe i can fix it from here. looks like a path issue. thanks!
