### ISSUE TITLE
SMA support?

### ISSUE THREAD

**Issue by Protektor-Desura** [RandomNinjaAtk/docker-sonarr-extended#8]
Is SMA scripts no longer supported in this Sonarr version? I have been relying on them to standardize my videos.

**Comment by RandomNinjaAtk** [comment]
SMA is installed, just no script is provided to use it. The extras features uses SMA.

**Comment by RandomNinjaAtk** [comment]
Example usage: https://github.com/RandomNinjaAtk/docker-sonarr-extended/blob/23540d74b7095624f7c109c2f7df751835670bfa/root/scripts/Extras.bash#L163
